apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: erostamas-rest-service-service-nw-policy
  labels:
    thelabel: iamrestserver
spec:
  podSelector:
    matchLabels:
      thelabel: iamrestserver
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            thelabel: iamk8sspy
      ports:
      - port: 5000
        protocol: TCP
