apiVersion: v1
kind: Service
metadata:
    name: erostamas-rest-service-service
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /metrics
      prometheus.io/port: "5000"
spec:
    type: NodePort
    ports:
    - name: http
      targetPort: 5000
      nodePort: 30020
      port: 5000
      protocol: TCP
    selector:
      app: erostamas-rest-service
